### ISSUE TITLE
Add Hackerrank font

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-github-leaderboad#11]
**Is your feature request related to a problem? Please describe.**
The font which hackerrank uses is looking really cool with numbers.

**Describe the solution you'd like**
1. Link this [Google Font](https://fonts.google.com/specimen/Source+Code+Pro?selection.family=Source+Code+Pro)
2. Add the font to
        - Socres
        - Ranks
        - Date times in the description modal

**Additional context**
Expected behavior:
![Screenshot 2019-12-27 at 20 07 21](https://user-images.githubusercontent.com/33048395/71520898-81968000-28e4-11ea-8a24-c210516f1b5e.jpg)
![Screenshot 2019-12-27 at 20 07 54](https://user-images.githubusercontent.com/33048395/71520920-94a95000-28e4-11ea-9e03-8b6685bfc10f.jpg)

**Comment by Gravewalker666** [comment]
Ill do this!!!!!!!!!!!

**Comment by Gravewalker666** [comment]
#16
