### ISSUE TITLE
PR template isn't working

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-github-leaderboad#29]
ThePR template isn't working.

- move `.github/PULL_REQUEST_TEMPLATE/pull_request_template.md` to .github/pull_request_template.md
- Delete `.github/PULL_REQUEST_TEMPLATE` directory

**Comment by Suthan97** [comment]
I’m a new comer. I did it. please review that
@jayasanka-sack

**Comment by jayasanka-sack** [comment]
Hi @Suthan97 ! We are glad to have you.  😇
Could you please open a pull request?

**Comment by Suthan97** [comment]
> Hi @Suthan97 ! We are glad to have you. 😇
> Could you please open a pull request?

Yeah. I’m apology for the late  . some trouble  with my network connection. I will open pull request asap. 😞
