### ISSUE TITLE
Update the README.md file with the latest URL

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-github-leaderboad#47]
**Describe the bug**
In the README.md file, the URL for SEF leaderboard is wrong.

**To Reproduce**
1. Go to the README.md file
2. Click on URL which is on the 1st section.

**Expected behavior**
The URL must be changed to the new URL which is [https://sef-github-leaderboard.herokuapp.com/](https://sef-github-leaderboard.herokuapp.com/)

**Comment by akeel230** [comment]
@janethavi this issue is fixed and a PR is started take a look .
