### ISSUE TITLE
Update the footer year 

### ISSUE THREAD

**Issue by janethavi** [sef-global/sef-github-leaderboad#53]
**Describe the bug**
On the footer of the [sef-leaderboad](https://sef-github-leaderboard.herokuapp.com/) site, the copyright year is not up to date. 

**To Reproduce**
1. Go to [https://sef-github-leaderboard.herokuapp.com/](https://sef-github-leaderboard.herokuapp.com/)
2. Scroll down to footer.
3. See the year 2020.

**Expected behavior**
The footer needs to be updated. Better write a script to get the current year. So we don't need to keep on updating the footer every year.

**Comment by deshankoswatte** [comment]
@janethavi Can I work on this?
