### ISSUE TITLE
Update the count score sql query and remove unwanted files

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-github-leaderboad#59]
**Is your feature request related to a problem? Please describe.**
- We need to update the count query and remove the unwanted files

**Describe the solution you'd like**
- Replace this query with the query that's currently commented out in [line 203](https://github.com/sef-global/sef-github-leaderboard/blob/0d98c319f6f4522f3de0b7b8105206778d65999c/src/main/java/org/sefglobal/githubleaderboad/api/dao/ScoreDAO.java#L203)
 https://github.com/sef-global/sef-github-leaderboard/blob/0d98c319f6f4522f3de0b7b8105206778d65999c/src/main/java/org/sefglobal/githubleaderboad/api/dao/ScoreDAO.java#L190
- Remove the following files
.travis
travis.yml
PROCFILE

**Comment by anjula-sack** [comment]
@tharindu37 can you work on this?

**Comment by Tharindu37** [comment]
@anjula-sack Sure
