### ISSUE TITLE
Add Pull Request Template

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/sef-github-leaderboad#9]
**Is your feature request related to a problem? Please describe.**
Currently, there is no PR template available so the receiving PRs are in different formats. So we can add a PR template in the repository.

**Describe the solution you'd like**
- Create a directory named `PULL_REQUEST_TEMPLATE` under `.github` directory
- Create a file named `pull_request_template.md` under the created directory.
- Add this content to the file: https://raw.githubusercontent.com/sef-global/sef-site/master/pull_request_template.md
- Remove `Screenshots` and `Preview link` sections from the content

**Additional context**
https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

**Comment by anjula-sack** [comment]
I'm working on it.
